In [1]:
import numpy as np

In [2]:
# R matrix
R = np.matrix([[-1,-1,-1,-1, 0,-1], # (S,A) -> R(0,4) = 0
               [-1,-1,-1, 0,-1,100],# (S,A) -> R(1,3) = 0; R(1,5) = 100 
               [-1,-1,-1, 0,-1,-1], # (S,A) -> R(2,3) = 0
               [-1, 0, 0,-1, 0,-1], # (S,A) -> R(3,1) = 0; R(3,2) = 0; R(3,4) = 0
               [ 0,-1,-1, 0,-1,100],# (S,A) -> R(4,0) = 0; R(4,3) = 0; R(4,5) = 100
               [-1,-1,-1,-1,-1,-1]])# (S,A) -> R(5,1) = 0; R(5,4) = 0; R(5,5) = 100

In [3]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,  -1,  -1,  -1]])

In [4]:
# Q matrix
Q = np.matrix(np.zeros([6, 6]))

In [5]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [6]:
# Gamma (Learning rate).
gamma = 0.8

In [7]:
# Initial state. (Usually to be chosen at random)
initial_state = 1

In [8]:
current_state_row = R[initial_state,]

In [9]:
current_state_row

matrix([[ -1,  -1,  -1,   0,  -1, 100]])

In [11]:
av_act = np.where(current_state_row >= 0)[1] 

In [12]:
av_act

array([3, 5], dtype=int64)

In [14]:
# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]                # Returns a matrix ([[ -1,  -1,  -1,   0,  -1, 100]])
    av_act = np.where(current_state_row >= 0)[1] # where([[ -1,  -1,  -1,   0,  -1, 100]]) >= 0 | array([3, 5])
    return av_act # return all available actions greater than zero | av_act = array([3, 5])

In [15]:
# Get available actions in the current state
available_act = available_actions(initial_state) # We summon the previous function to obtain av_act

In [16]:
available_act

array([3, 5], dtype=int64)

In [17]:
next_action = int(np.random.choice(available_act, 1))

In [18]:
next_action

3

In [19]:
# This function chooses at random which action to be performed within the range
# of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act, 1))
    return next_action

In [20]:
# Sample next action to be performed
action = sample_next_action(available_act)

In [21]:
action

3

In [28]:
max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
max_index

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [29]:
Q[action,] # action = 3

matrix([[0., 0., 0., 0., 0., 0.]])

In [30]:
np.max(Q[action,])

0.0

In [23]:
    if max_index.shape[0] > 1:
        max_index = int(np. random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
max_index

4

In [31]:
max_index.shape[0]

6

In [32]:
max_index = int(np. random.choice(max_index, size = 1))
max_index

3

In [37]:
max_value = Q[action, max_index]

In [35]:
current_state = 1

In [38]:
# Q learning formula
Q[current_state, action] = R[current_state, action] + gamma * max_value
Q[current_state, action]

0.0